#server port
server:
  port: 8761
#It is not a client, it is a server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    instance:
      hostname=localhost:
  #EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.:
  renewalPercentThreshold: 0.85
#application name
spring:
  application:
    name: SERVER-REGISTRY